/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

uint8_t variableGlobal = 0;


int main(void)
{
	uint8_t variablelocal = 0;
    /* Loop forever */
	for(;;);
	return 0;
}
/*Funcion para sumar a una variable global */
void  sumaGlobal(void){

}
/*Funcion para sumar a una variable local */
void sumalocal(void){

}
