/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define SET 	1
#define RESET 	0

void verificarFor(void);
uint8_t variableN(uint8_t var);
uint16_t calculadora(uint16_t int1, uint8_t operacion, uint16_t int2);

uint8_t flag3 = 0;
uint8_t flag6 = 0;
uint8_t flag9 = 0;

enum {
	SUMA = 0, RESTA, MULTIPLICACION, DIVISION, MODULO
};

int main(void) {

	verificarFor();

	uint16_t resSuma = calculadora(5, MULTIPLICACION, 6);
	(void) resSuma;

	uint8_t varR = 0;
	(void) varR;
	varR = variableN(280);

	while (1)
		;
}

void verificarFor(void) {
	uint8_t contador = 0;

	for (uint8_t i = 0; i < 10; i = i + 1) {
		contador = contador + 1;

		if (contador < 3) {
			flag3 = 1;
		}

		else if (contador >= 3 && contador < 6) {
			flag3 = 0;
			flag6 = 1;
		}

		else {
			flag6 = 0;
			flag9 = 1;
		}
	}
}

uint16_t calculadora(uint16_t int1, uint8_t operacion, uint16_t int2) {
	uint16_t res = 0;
	switch (operacion) {
	case SUMA:
		res = int1 + int2;
		break;
	case RESTA:
		res = int1 - int2;
		break;
	case MULTIPLICACION:
		res = int1 * int2;
		break;
	default:
		break;
	}
	return res;
}

uint8_t variableN(uint8_t var) {
	uint8_t contador = 0;
	do {
		contador = contador + 1;
	} while (contador < var);
	return contador;
}

